version: "3.9"

services:
  app:
    image: azul/zulu-openjdk:17
    container_name: spring-app
    working_dir: /app
    volumes:
      - ./:/app
    command: ["sh", "-c", "chmod +x mvnw && ./mvnw spring-boot:run"]
    ports:
      - "${APP_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:${DB_PORT};databaseName=${DB_NAME};encrypt=false
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "${DB_PORT}:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASS}"
      MSSQL_PID: "Express"
    volumes:
      - mssqldata:/var/opt/mssql
      - ./init-sql:/init-sql

  db-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: sql-init
    depends_on:
      - db
    env_file:
      - .env
    entrypoint: [ "/bin/bash", "/init-sql/entrypoint.sh" ]
    volumes:
      - ./init-sql:/init-sql

volumes:
  mssqldata:
